name: dse-static
on:
  workflow_dispatch:
    inputs:
      edition:
        description: digital edition name
        required: false
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: extract existing data
      run: |
        cd dse-static-pipeline
        ./extract_existing.sh
        echo "### Existing data:"
        ls -1 data
    - name: create missing verticals
      run: |
        cd dse-static-pipeline
        python3 -m venv env
        source env/bin/activate
        pip3 install -U -r requirements.txt
        PARAM="-s"
        if [ -n "${{ inputs.edition }}" ] ; then 
          PARAM="-e ${{ inputs.edition }}"
        fi
        python3 create_verticals.py -c config_sample.yaml $PARAM
    - name: compile corpora
      run: |
        cd dse-static-pipeline
        ./compile_corp.sh
    - name: build updated image
      run: |
        cd dse-static-pipeline
        ./build_image.sh
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      run: docker push acdhch/noske-fcs-gams-dse-static:latest


